In [10]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

np.random.seed(30)

In [27]:
# How likely is it that you roll doubles when rolling two dice?
n_trials= nrows =10000
n_dice = ncol = 2

rolls = np.random.choice([1,2,3,4,5,6], size=(n_trials,n_dice))
rolls

array([[6, 3],
       [6, 5],
       [6, 3],
       ...,
       [2, 2],
       [1, 5],
       [6, 1]])

In [43]:
dice = pd.DataFrame(rolls)
dice

0  1
0     6  3
1     6  5
2     6  3
3     4  1
4     6  2
...  .. ..
9995  6  1
9996  4  5
9997  2  2
9998  1  5
9999  6  1

[10000 rows x 2 columns]

In [53]:
(dice[0] == dice[1]).mean()

0.1634

In [73]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

flip = np.random.choice(['head','tail'],size =(10000, 8))
df = pd.DataFrame(flip)
df.head()

0     1     2     3     4     5     6     7
0  head  tail  head  head  tail  head  head  head
1  head  head  head  head  head  head  head  head
2  head  tail  tail  head  head  head  tail  head
3  head  tail  head  head  tail  tail  head  head
4  tail  tail  head  head  tail  tail  tail  head

In [61]:
df['n_heads'] = (df=='head').sum(axis=1)
df.head()

0     1     2     3     4     5     6     7  n_heads
0  head  tail  head  head  tail  tail  tail  head        4
1  tail  tail  head  tail  head  tail  head  head        4
2  head  tail  tail  tail  head  head  head  tail        4
3  tail  tail  head  tail  tail  tail  head  tail        2
4  tail  tail  head  head  tail  tail  head  head        4

In [64]:
(df.n_heads == 3).mean()

0.2193

In [65]:
(df.n_heads > 3).mean()

0.6415

In [100]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?
# web development =.75
# data science = .25
cohort = np.random.random(size =(10000,2))

cohort




array([[0.56541087, 0.16239929],
       [0.42530213, 0.68438748],
       [0.10184655, 0.03210951],
       ...,
       [0.11550303, 0.9447577 ],
       [0.80964001, 0.55572932],
       [0.35698903, 0.34315281]])

In [103]:
ds = cohort <= .25
ds

array([[False,  True],
       [False, False],
       [ True,  True],
       ...,
       [ True, False],
       [False, False],
       [False, False]])

In [104]:
(ds.sum(axis=1) == 2).mean()

0.0633

In [ ]:
# Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. 
# If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [111]:
poptarts = np.random.normal(3, 1.5,(10000,5))
p_friday = (poptarts.sum(axis=1)<17).mean()
p_friday

0.726

In [115]:
# Compare Heights

# Men have an average height of 178 cm and standard deviation of 8cm.
men=np.random.normal(178, 8,10000)
men

array([176.80436563, 179.08597626, 170.16140914, ..., 175.25720954,
       171.18097787, 173.13602276])

In [116]:
# Women have a mean of 170, sd = 6cm.
female = np.random.normal(170, 6,10000)
female

array([166.24328878, 163.94855447, 171.2234598 , ..., 175.5355782 ,
       169.96673324, 179.94783405])

In [ ]:
# If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [120]:
(female > men).mean()

0.2129

In [149]:
# When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. 
# What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?
fail= (1/250)
fifty = np.random.random(size=(10000,50))
fifty


array([[0.88642492, 0.1165982 , 0.51007592, ..., 0.16659976, 0.73185713,
        0.04193223],
       [0.76024755, 0.345594  , 0.23736418, ..., 0.63021392, 0.3989309 ,
        0.9733492 ],
       [0.25728477, 0.64067305, 0.19328486, ..., 0.14278487, 0.97841271,
        0.65958042],
       ...,
       [0.887537  , 0.35132124, 0.24720244, ..., 0.22897366, 0.13068378,
        0.5797821 ],
       [0.36421398, 0.73723419, 0.51890836, ..., 0.16631998, 0.24482615,
        0.32495632],
       [0.74826257, 0.85668851, 0.42304589, ..., 0.76136518, 0.60439398,
        0.95040881]])

In [186]:
fail_fifty = ((fifty > fail).sum(axis=1)==50).mean()
fail_fifty

0.821

In [185]:
#for 100
fail_hundred = ((np.random.random(size=(10000,100))> fail).sum(axis=1)== 100).mean()
fail_hundred

0.6654

In [190]:
# What is the probability that we observe an installation issue within the first 150 students that download anaconda?
_150 = np.random.random(size=(10000,150))
_150 < fail
fail_150 = ((_150 < fail).sum(axis=1) > 0).mean()
fail_150


0.4571

In [184]:
# How likely is it that 450 students all download anaconda without an issue?
fail_450 = ((np.random.random(size=(10000,450))> fail).sum(axis=1)== 450).mean()
fail_450

0.1612

In [180]:
# There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

# How likely is it that a food truck will show up sometime this week?
atleast1= .7
three_truck = np.random.random(size=(10000,3))
three_truck



array([[0.52423333, 0.54956349, 0.34161603],
       [0.48638473, 0.0078827 , 0.06806659],
       [0.51332536, 0.28887272, 0.12156343],
       ...,
       [0.79685525, 0.1912343 , 0.26756588],
       [0.3205073 , 0.08216471, 0.97070797],
       [0.63470239, 0.56894587, 0.53948419]])

In [187]:
no_truck =((three_truck > atleast1).sum(axis=1)== 0).mean()
no_truck

0.3464

In [188]:
# How likely is it that a food truck will show up sometime this week?
seven_days = np.random.random(size=(10000,7)) > atleast1
(seven_days.sum(axis=1)>=1).mean()

0.9125

In [ ]:
# If 23 people are in the same room, what are the odds that two of them share a birthday? 
# What if it's 20 people? 40?
np.random.random((10000,))